# Generated by Django 2.2.3 on 2019-07-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='messages',
        ),
        migrations.AddField(
            model_name='lead',
            name='message',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
